<?php

namespace Database\Seeders;

use App\Models\Plan;
use Illuminate\Database\Seeder;

class PlanSeeder extends Seeder
{
    public function run(): void
    {
        $plans = [
            [
                'name' => 'Starter Monthly',
                'slug' => 'starter-monthly',
                'description' => 'Launch one industry chatbot workspace with the essentials.',
                'amount' => '9.99',
                'amount_minor' => 999,
                'currency' => 'USD',
                'billing_interval' => 'month',
                'stripe_price_id' => 'price_1TmI2U1Oz8XVPHYWFE6vveyB',
                'stripe_product_id' => 'prod_UlphTeaK92H5er',
                'features' => [
                    'Basic chatbot',
                    'Conversation history',
                    'Email support',
                ],
                'limits' => [
                    'organizations' => 1,
                    'projects' => 3,
                    'storage_bytes' => 5368709120,
                    'chatbot_messages_monthly' => 10000,
                    'team_members' => 5,
                    'api_requests_monthly' => 10000,
                ],
                'entitlements' => [
                    'chatbot.basic',
                    'support.email',
                    'conversation_history.enabled',
                ],
                'is_popular' => false,
                'sort_order' => 1,
            ],
            [
                'name' => 'Pro Monthly',
                'slug' => 'pro-monthly',
                'description' => 'Build advanced chatbot experiences in one industry workspace.',
                'amount' => '29.99',
                'amount_minor' => 2999,
                'currency' => 'USD',
                'billing_interval' => 'month',
                'stripe_price_id' => 'price_1TmIPc1Oz8XVPHYW2vf5KFem',
                'stripe_product_id' => 'prod_Ulq5Rxe3Hpsn1k',
                'features' => [
                    'Chatbot automation',
                    'Conversation history',
                    'Priority support',
                ],
                'limits' => [
                    'organizations' => 1,
                    'projects' => 10,
                    'storage_bytes' => 26843545600,
                    'chatbot_messages_monthly' => 50000,
                    'team_members' => 15,
                    'api_requests_monthly' => 100000,
                ],
                'entitlements' => [
                    'chatbot.automation',
                    'chatbot.advanced',
                    'analytics.advanced',
                    'conversation_history.enabled',
                    'support.priority',
                ],
                'is_popular' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Pro Yearly',
                'slug' => 'pro-yearly',
                'description' => 'An annual plan for one growing workspace that needs more capacity.',
                'amount' => '279.00',
                'amount_minor' => 27900,
                'currency' => 'USD',
                'billing_interval' => 'year',
                'stripe_price_id' => 'price_1TmIPd1Oz8XVPHYWV4w77fJg',
                'stripe_product_id' => 'prod_Ulq5Rxe3Hpsn1k',
                'features' => [
                    'Chatbot automation',
                    'Conversation history',
                    'Priority support',
                ],
                'limits' => [
                    'organizations' => 1,
                    'projects' => 10,
                    'storage_bytes' => 26843545600,
                    'chatbot_messages_monthly' => 50000,
                    'team_members' => 15,
                    'api_requests_monthly' => 100000,
                ],
                'entitlements' => [
                    'chatbot.automation',
                    'chatbot.advanced',
                    'analytics.advanced',
                    'conversation_history.enabled',
                    'support.priority',
                ],
                'is_popular' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Business Yearly',
                'slug' => 'business-yearly',
                'description' => 'Run advanced chatbot workflows in one organization.',
                'amount' => '299.99',
                'amount_minor' => 29999,
                'currency' => 'USD',
                'billing_interval' => 'year',
                'stripe_price_id' => 'price_1TmIUi1Oz8XVPHYWrVJ52Bbh',
                'stripe_product_id' => 'prod_UlqB8s4DgeE0tf',
                'features' => [
                    'Advanced chatbot workflows',
                    'Chatbot analytics',
                    'Priority support',
                ],
                'limits' => [
                    'organizations' => 1,
                    'projects' => 50,
                    'storage_bytes' => 107374182400,
                    'chatbot_messages_monthly' => 250000,
                    'team_members' => 50,
                    'api_requests_monthly' => 500000,
                ],
                'entitlements' => [
                    'chatbot.automation',
                    'chatbot.advanced',
                    'chatbot.analytics',
                    'conversation_history.enabled',
                    'support.priority',
                ],
                'is_popular' => false,
                'sort_order' => 4,
            ],
            [
                'name' => 'Enterprise Monthly',
                'slug' => 'enterprise-monthly',
                'description' => 'Create one industry workspace with custom chatbot capabilities.',
                'amount' => '99.00',
                'amount_minor' => 9900,
                'currency' => 'USD',
                'billing_interval' => 'month',
                'stripe_price_id' => 'price_1TmIda1Oz8XVPHYW7Teh4Uct',
                'stripe_product_id' => 'prod_UlqIShYZ8kR2mg',
                'features' => [
                    'Custom chatbot workflows',
                    'Chatbot integrations',
                    'Dedicated support',
                ],
                'limits' => [
                    'organizations' => 1,
                    'projects' => 100,
                    'storage_bytes' => 268435456000,
                    'chatbot_messages_monthly' => 'unlimited',
                    'team_members' => 'unlimited',
                    'api_requests_monthly' => 'unlimited',
                ],
                'entitlements' => [
                    'chatbot.custom_workflows',
                    'chatbot.advanced',
                    'chatbot.analytics',
                    'analytics.advanced',
                    'support.priority',
                    'integrations.enabled',
                    'support.dedicated',
                ],
                'is_popular' => false,
                'sort_order' => 5,
            ],
            [
                'name' => 'Enterprise Yearly',
                'slug' => 'enterprise-yearly',
                'description' => 'An annual enterprise plan for one organization with larger workloads.',
                'amount' => '949.00',
                'amount_minor' => 94900,
                'currency' => 'USD',
                'billing_interval' => 'year',
                'stripe_price_id' => 'price_1TmIcD1Oz8XVPHYWNIUAJlsK',
                'stripe_product_id' => 'prod_UlqIShYZ8kR2mg',
                'features' => [
                    'Custom chatbot workflows',
                    'Chatbot integrations',
                    'Dedicated support',
                ],
                'limits' => [
                    'organizations' => 1,
                    'projects' => 100,
                    'storage_bytes' => 268435456000,
                    'chatbot_messages_monthly' => 'unlimited',
                    'team_members' => 'unlimited',
                    'api_requests_monthly' => 'unlimited',
                ],
                'entitlements' => [
                    'chatbot.custom_workflows',
                    'chatbot.advanced',
                    'chatbot.analytics',
                    'analytics.advanced',
                    'support.priority',
                    'integrations.enabled',
                    'support.dedicated',
                ],
                'is_popular' => false,
                'sort_order' => 6,
            ],
        ];

        foreach ($plans as $plan) {
            Plan::updateOrCreate(
                ['slug' => $plan['slug']],
                [
                    'name' => $plan['name'],
                    'description' => $plan['description'],
                    'amount' => $plan['amount'],
                    'amount_minor' => $plan['amount_minor'],
                    'currency' => $plan['currency'],
                    'billing_interval' => $plan['billing_interval'],
                    'stripe_price_id' => $plan['stripe_price_id'],
                    'is_active' => true,
                    'features' => $plan['features'],
                    'metadata' => [
                        'stripe_product_id' => $plan['stripe_product_id'],
                        'entitlements' => $plan['entitlements'],
                    ],
                    'stripe_plan_id' => null,
                    'price' => $plan['amount'],
                    'interval' => $plan['billing_interval'],
                    'limits' => $plan['limits'],
                    'is_popular' => $plan['is_popular'],
                    'sort_order' => $plan['sort_order'],
                ],
            );
        }
    }
}
