import { ArrowUpRight, Code2, Layers3, ShieldCheck, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';

const principles = [
  ['01', 'Clarity over cleverness', 'A foundation should disappear into the work. Every layer is readable, documented, and yours to change.'],
  ['02', 'Secure by default', 'The server owns auth, billing, permissions, and tenant boundaries, so the product stays trustworthy as it grows.'],
  ['03', 'Ship in the open', 'LaunchStack is built around real product milestones: account, workspace, payment, and the next customer.'],
];

export default function About() {
  return <div>
    <section className="border-b border-white/10 px-5 pb-20 pt-24 sm:px-8 sm:pb-28 sm:pt-32"><div className="public-container grid gap-10 lg:grid-cols-[1.3fr_.7fr]"><div><p className="public-kicker">About LaunchStack</p><h1 className="mt-6 max-w-4xl text-5xl font-black leading-[.95] tracking-[-.07em] text-white sm:text-7xl">A clearer way<br /><span className="text-[#d7f36b]">to work.</span></h1></div><p className="max-w-sm self-end text-lg leading-8 text-slate-300">LaunchStack gives modern teams a focused workspace for planning projects, assigning tasks, and keeping progress visible.</p></div></section>
    <section className="public-container px-5 py-20 sm:px-8 sm:py-28"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="public-kicker">Our point of view</p><div className="mt-8 flex gap-4"><Sparkles className="mt-1 h-5 w-5 shrink-0 text-[#d7f36b]" /><p className="text-2xl font-bold leading-9 text-white">Good project management makes the next action obvious.</p></div></div><div className="space-y-6 text-lg leading-8 text-slate-300"><p>Teams do their best work when projects, tasks, owners, and deadlines are visible in the same place. Less time is spent searching for context, and more time goes into moving the work forward.</p><p>LaunchStack is built around that simple idea: one secure workspace where teams can organize delivery, collaborate clearly, and grow into more structured ways of working.</p></div></div></section>
    <section className="border-y border-white/10 px-5 py-20 sm:px-8 sm:py-28"><div className="public-container"><p className="public-kicker">What we optimize for</p><div className="mt-12 divide-y divide-white/10 border-t border-white/10">{principles.map(([number, title, description]) => <article key={number} className="grid gap-5 py-7 sm:grid-cols-[5rem_1fr_1fr] sm:items-start"><span className="public-outline-number text-3xl font-black">{number}</span><h2 className="text-xl font-bold text-white">{title}</h2><p className="text-sm leading-6 text-slate-400">{description}</p></article>)}</div></div></section>
    <section className="public-container px-5 py-20 sm:px-8 sm:py-28"><div className="grid gap-8 sm:grid-cols-3"><div className="public-panel p-6"><ShieldCheck className="h-5 w-5 text-[#d7f36b]" /><p className="mt-10 text-3xl font-black text-white">Server-first</p><p className="mt-2 text-sm text-slate-400">Auth and billing stay where they belong.</p></div><div className="public-panel p-6"><Code2 className="h-5 w-5 text-[#d7f36b]" /><p className="mt-10 text-3xl font-black text-white">Type-safe</p><p className="mt-2 text-sm text-slate-400">React, TypeScript, Laravel, and APIs with intent.</p></div><div className="public-panel p-6"><Layers3 className="h-5 w-5 text-[#d7f36b]" /><p className="mt-10 text-3xl font-black text-white">Extensible</p><p className="mt-2 text-sm text-slate-400">A starting line, never a ceiling.</p></div></div><div className="mt-16 flex flex-col items-start justify-between gap-6 border-t border-white/10 pt-10 sm:flex-row sm:items-center"><p className="text-xl font-bold text-white">Ready to make your first commit count?</p><Link to="/register" className="public-button public-button--lime">Start building <ArrowUpRight className="h-4 w-4" /></Link></div></section>
  </div>;
}
