import { ArrowUpRight, Bot, BookOpenText, ChartNoAxesCombined, Code2, LockKeyhole, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';

const assistants = [
  { number: '01', icon: BookOpenText, name: 'Launch Guide', description: 'A product-aware guide for finding the right feature, setup path, or next step in your workspace.', examples: 'Setup questions · Product guidance · Account help' },
  { number: '02', icon: ChartNoAxesCombined, name: 'Growth Analyst', description: 'A future assistant for turning workspace activity into useful signals, summaries, and decisions.', examples: 'Trend summaries · Workspace insights · Weekly reports' },
  { number: '03', icon: Code2, name: 'Build Partner', description: 'A developer-focused companion for understanding your LaunchStack foundation and moving faster.', examples: 'Architecture questions · API guidance · Implementation ideas' },
];

export default function Chatbots() {
  return <div>
    <section className="border-b border-white/10 px-5 pb-20 pt-24 sm:px-8 sm:pb-28 sm:pt-32"><div className="public-container grid gap-10 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><div><p className="public-kicker flex items-center gap-3"><span className="h-px w-8 bg-[#d7f36b]" /> Future product line</p><h1 className="mt-6 max-w-4xl text-5xl font-black leading-[.95] tracking-[-.07em] text-white sm:text-7xl">Helpful by design.<br /><span className="text-[#d7f36b]">Coming soon.</span></h1></div><div className="max-w-sm lg:justify-self-end"><div className="mb-5 flex h-12 w-12 items-center justify-center border border-[#d7f36b]/40 text-[#d7f36b]"><Bot className="h-6 w-6" /></div><p className="text-lg leading-8 text-slate-300">We are designing a small family of focused AI assistants for LaunchStack. They are not live yet — and we will only ship them when they are genuinely useful.</p></div></div></section>
    <section className="public-container px-5 py-20 sm:px-8 sm:py-28"><div className="flex flex-col justify-between gap-5 border-b border-white/10 pb-8 sm:flex-row sm:items-end"><div><p className="public-kicker">The roadmap</p><h2 className="mt-4 text-4xl font-black tracking-[-.06em] text-white sm:text-5xl">One job per bot.</h2></div><p className="max-w-xs text-sm leading-6 text-slate-400">No generic chatbot. Each assistant will have a clear role, clear boundaries, and a human handoff when needed.</p></div><div className="mt-12 grid border-l border-t border-white/10 md:grid-cols-3">{assistants.map(({ number, icon: Icon, name, description, examples }) => <article key={name} className="flex min-h-[20rem] flex-col border-b border-r border-white/10 p-6 sm:p-8"><div className="flex items-center justify-between"><Icon className="h-5 w-5 text-[#d7f36b]" aria-hidden="true" /><span className="public-outline-number text-3xl font-black">{number}</span></div><div className="mt-auto pt-20"><span className="inline-flex items-center gap-2 border border-[#d7f36b]/30 px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.14em] text-[#d7f36b]"><Sparkles className="h-3 w-3" /> Coming soon</span><h3 className="mt-5 text-2xl font-bold text-white">{name}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{description}</p><p className="mt-6 border-t border-white/10 pt-4 text-xs leading-5 text-slate-500">{examples}</p></div></article>)}</div></section>
    <section className="border-y border-white/10 px-5 py-20 sm:px-8 sm:py-24"><div className="public-container grid gap-8 sm:grid-cols-[1fr_auto] sm:items-center"><div className="flex gap-4"><LockKeyhole className="mt-1 h-5 w-5 shrink-0 text-[#d7f36b]" /><div><h2 className="text-2xl font-bold text-white">Built with trust in mind</h2><p className="mt-2 max-w-xl text-sm leading-6 text-slate-400">When these assistants arrive, your data will stay scoped to your organization, with safe answers and an easy path to human support.</p></div></div><Link to="/contact" className="public-button public-button--quiet">Ask about the roadmap <ArrowUpRight className="h-4 w-4" /></Link></div></section>
  </div>;
}
