import LegalPage, { type LegalSection } from './LegalPage';

const sections: LegalSection[] = [
  { id: 'information', title: '1. Information we collect', content: <><p>We may collect account information such as your name, email address, authentication details, organization membership, and settings you provide when using LaunchStack.</p><p>We also collect information needed to operate the service, including support messages, subscription and payment status, security events, and basic technical information such as browser or device details.</p></> },
  { id: 'use', title: '2. How we use information', content: <><p>We use information to provide, secure, maintain, and improve LaunchStack; authenticate accounts; manage organizations and permissions; process subscriptions; respond to support requests; and communicate important service or security updates.</p><p>We do not use private organization content to advertise to you.</p></> },
  { id: 'sharing', title: '3. When information is shared', content: <><p>We may share information with service providers that help us host the application, process payments, deliver email, or provide infrastructure. These providers receive only the information needed for their assigned service.</p><p>We may also disclose information when required by law, to protect the security of the service, or as part of a business transfer.</p></> },
  { id: 'security', title: '4. Security and retention', content: <><p>We use reasonable technical and organizational safeguards to protect account and organization information. No online service can guarantee absolute security.</p><p>We retain information for as long as needed to provide the service, meet legal obligations, resolve disputes, and enforce agreements. Retention periods may vary by data type.</p></> },
  { id: 'rights', title: '5. Your choices', content: <><p>You may update certain account information from your dashboard. You may also contact us to request access, correction, export, or deletion of personal information, subject to applicable legal requirements.</p><p>Critical service, billing, and security messages may still be sent even when optional notifications are disabled.</p></> },
  { id: 'contact', title: '6. Contact', content: <p>Questions about this policy can be sent through our <a className="text-[#d7f36b] underline underline-offset-4" href="/contact">Contact page</a>. We will update this page when our practices materially change.</p> },
];

export default function PrivacyPolicy() { return <LegalPage kind="privacy" eyebrow="Legal / Privacy" title="Privacy Policy" intro="A clear starting point for how LaunchStack handles account, organization, and support information." updated="September 1, 2026" sections={sections} />; }
