import LegalPage, { type LegalSection } from './LegalPage';

const sections: LegalSection[] = [
  { id: 'scope', title: '1. Scope and information we collect', content: <><p>This page describes the information LaunchStack processes when you visit the public site, create an account, use a workspace, contact support, or purchase a plan.</p><p>Depending on how you use the service, this can include your name, email address, password or authentication data, email-verification and password-reset records, organization details, membership and role information, direct permissions, invitations, notification preferences, support messages, and activity associated with your account or organization.</p><p>Billing records include plan, subscription, payment status, invoice, refund, and provider-reference information. LaunchStack’s application does not need to store your full payment-card number to maintain these records; payment details are handled through the configured payment provider’s checkout flow.</p></> },
  { id: 'use', title: '2. How we use information', content: <><p>We use information to create and authenticate accounts; verify email addresses; operate organizations and tenant-scoped workspaces; enforce roles and granular permissions; send invitations and service notifications; provide support; process subscriptions and payments; prevent abuse; maintain security; troubleshoot failures; and improve the service.</p><p>Organization information is used to provide the workspace to its authorized members. Access to organization data is controlled by authenticated membership, role, and permission checks.</p></> },
  { id: 'storage', title: '3. Cookies, local storage, and technical records', content: <><p>The application uses browser storage for authentication state and the selected organization preference. The backend is configured to use session cookies and may use cookies required for application operation. These technologies support sign-in, session handling, and remembering workspace context.</p><p>LaunchStack does not currently advertise or document a separate analytics or advertising-cookie program in this application. If that changes, this policy should be updated before the change is released.</p><p>Operational logs and security records may contain request, authentication, billing, notification, or error context needed to operate and protect the service. We do not intentionally include secrets in user-facing responses.</p></> },
  { id: 'sharing', title: '4. When information is shared', content: <><p>We may share the minimum information needed with providers configured to host the application, deliver email, process payments, or provide infrastructure. The repository confirms Stripe integration for checkout and webhook processing and configurable mail transports; the active provider depends on deployment configuration.</p><p>We may also disclose information when required by law, to protect the rights and security of users or the service, or in connection with a merger, acquisition, financing, or transfer of the service.</p></> },
  { id: 'retention', title: '5. Security, retention, and deletion', content: <><p>We use authentication, tenant access checks, role and permission checks, payment-provider webhook verification, throttling, and application safeguards intended to protect information. No online service can guarantee absolute security.</p><p>Information is retained for as long as needed to provide the service, operate account and billing records, resolve disputes, enforce agreements, and meet legal or security obligations. Exact retention periods depend on the data type and deployment configuration and are not specified by the application code.</p><p>You can request correction, export, or deletion of personal information through the <a className="text-[#d7f36b] underline underline-offset-4" href="/contact">Contact page</a>. We may need to verify the request and may retain information where the law or legitimate operational requirements require it.</p></> },
  { id: 'choices', title: '6. Your choices and communications', content: <><p>You can update available account and organization information from the dashboard. Optional notification preferences may be changed where the product provides those controls. Critical account, security, billing, and invitation messages may still be sent when optional notifications are disabled.</p><p>You are responsible for ensuring that information you provide about organization members and invitation recipients is shared lawfully and that those people receive any notices required by your organization.</p></> },
  { id: 'contact', title: '7. Contact and updates', content: <p>Questions, privacy requests, and concerns about this policy can be submitted through our <a className="text-[#d7f36b] underline underline-offset-4" href="/contact">Contact page</a>. We will update this page when our information practices materially change. A qualified lawyer should review this policy for the operating jurisdictions and final business contact details before publication.</p> },
];

export default function PrivacyPolicy() { return <LegalPage kind="privacy" eyebrow="Legal / Privacy" title="Privacy Policy" intro="How LaunchStack handles account, workspace, billing, support, and operational information." updated="September 4, 2026" sections={sections} />; }
