import LegalPage, { type LegalSection } from './LegalPage';

const sections: LegalSection[] = [
  { id: 'acceptance', title: '1. Acceptance and eligibility', content: <><p>By creating an account or using LaunchStack, you agree to these terms and the Privacy Policy. If you use LaunchStack for an organization, you confirm that you have authority to accept these terms for that organization.</p><p>You must provide accurate information, keep your account credentials secure, and use the service only where you are legally permitted to do so.</p></> },
  { id: 'service', title: '2. The service and workspace model', content: <><p>LaunchStack provides account, organization, team, subscription, billing, notification, support, and related SaaS workspace features. An organization is a tenant-scoped workspace. Access depends on active membership and the role and permissions assigned to a member.</p><p>Organization owners and authorized administrators may invite members, manage membership, and assign organization-specific permissions. A member must not use another person’s account or attempt to bypass tenant, role, or permission controls.</p><p>We may change, improve, suspend, or discontinue parts of the service as the product evolves. We will make reasonable efforts to communicate material changes where appropriate.</p></> },
  { id: 'acceptable-use', title: '3. Acceptable use and security', content: <><p>You may not misuse the service, interfere with its operation, introduce malicious code, probe or bypass security controls, access another organization without authorization, abuse invitations or notifications, reverse engineer restricted parts of the service, or use LaunchStack in violation of applicable law.</p><p>You must promptly notify us through the <a className="text-[#d7f36b] underline underline-offset-4" href="/contact">Contact page</a> if you believe your account or organization access has been compromised.</p></> },
  { id: 'billing', title: '4. Plans, billing, and organization limits', content: <><p>Plans, prices, billing intervals, features, taxes, and organization limits are displayed in the LaunchStack billing or checkout flow. Subscriptions and payments belong to the authenticated account owner, not to a selected organization.</p><p>Free plans may be activated within the application. Paid plans may create a pending payment and use Stripe Checkout. The payment provider sends a verified webhook before LaunchStack treats the payment and subscription as active. Payment history may include payment, invoice, refund, and failure statuses.</p><p>Cancellation may occur at the end of the current billing period or immediately, depending on the action selected and applicable plan rules. Refunds may be full, partial, pending, or failed and are subject to the applicable billing decision. Existing organizations are not silently deleted when a plan limit changes; new organization creation may be blocked while an account is over its limit.</p></> },
  { id: 'content', title: '5. Your content and feedback', content: <><p>You retain rights to information and content you submit to LaunchStack. You grant us the limited rights needed to host, process, secure, back up where configured, and display that content to provide the service.</p><p>You are responsible for having the necessary rights and permissions for submitted content and for complying with your organization’s policies. Do not submit content that is unlawful, infringing, malicious, or unauthorized.</p></> },
  { id: 'suspension', title: '6. Suspension and termination', content: <><p>We may restrict, suspend, or terminate access when reasonably necessary to protect the service, investigate abuse or security issues, enforce these terms, comply with law, or address failed or cancelled billing.</p><p>Organization access may also change when membership is removed, an invitation is revoked or expires, an organization is deactivated, or a user’s role or permissions are changed. Termination does not automatically transfer or delete organization data. Data handling after termination depends on the applicable account, organization, legal, and operational requirements.</p></> },
  { id: 'availability', title: '7. Availability and warranties', content: <p>LaunchStack is provided on an as-available basis. To the maximum extent permitted by law, we disclaim warranties not expressly stated in these terms. We do not guarantee that the service will always be uninterrupted, error-free, secure, or suitable for every use case. Nothing in these terms limits rights that cannot legally be limited.</p> },
  { id: 'liability', title: '8. Liability and governing law', content: <p>Any limitation of liability, indemnity, dispute-resolution process, governing law, jurisdiction, and business-entity details must be completed and reviewed by qualified legal counsel for the jurisdictions where LaunchStack operates. Those details are not established in the application code, so they are intentionally not guessed here.</p> },
  { id: 'contact', title: '9. Contact and updates', content: <p>Questions about these terms can be submitted through our <a className="text-[#d7f36b] underline underline-offset-4" href="/contact">Contact page</a>. We may update these terms as the service or applicable requirements change. Material changes should be reviewed and communicated before taking effect where appropriate.</p> },
];

export default function TermsOfService() { return <LegalPage kind="terms" eyebrow="Legal / Terms" title="Terms of Service" intro="The rules and expectations for using LaunchStack accounts, workspaces, teams, and subscriptions." updated="September 4, 2026" sections={sections} />; }
